# Your Name or Company
title: Green Team Services

# Description of your website. This is used for social sharing.
description:  Green Team Services is to help you automate your security capabilities.

# A brief blurb about yourself
content: Green Team Services AppSec focused is to help you automate your security capabilities. Green Team consists of ongoing structured interactions between the Blue Team and members of the software team (Yellow Team). The ultimate goal is to improve code-based and design-based defence capability for detection, incident response and data forensics.
 - We help you improve your logging capability working to standardise and prioritise what is important
 - We help you provide better data to the DFIR Team
 - We help you define a better change management process
 - We will discuss solutions and improvements for
 - DFIR Output
 - Logging improvements
 - Log content / events
 - Log generation standardising
 - Change Management
 - Integrity Monitoring
 - Malware Protection
 - Full coverage monitoring
 
# Add your social links
# social:
#   - platform: github
#     url: https://github.com/brianmaierjr
#   - platform: facebook
#     url: https://facebook.com/brianmaierjr
#   - platform: twitter
#     url: https://twitter.com/brianmaierjr
#   - platform: linkedin
#     url: brianmaierjr

# General settings
baseurl: "/green" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "G-3CLTHF25DG" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
